apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: apisix
    releaseName: apisix
    version: 2.9.0
    repo: https://charts.apiseven.com
    namespace: iam
    includeCRDs: true
    skipTests: true
    valuesInline:
      service:
        http:
          nodePort: 31080
        tls:
          nodePort: 31443
      ingress:
        enabled: false
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - host: apisix.endvrpad.rconway.uk
            paths:
              - /
        tls:
          - hosts:
              - apisix.endvrpad.rconway.uk
            secretName: apisix-tls
      apisix:
        enableIPv6: false
        enableServerTokens: false
        ssl:
          enabled: true
          fallbackSNI: endvrpad.rconway.uk
      etcd:
        # replicaCount: 1
        persistence:
          storageClass: standard
          size: 8Gi
      dashboard:
        enabled: true
      ingress-controller:
        enabled: true
        config:
          apisix:
            serviceNamespace: iam
