---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: iam
spec:
  dnsNames:
    - iam-auth.endvrpad.rconway.uk
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: keycloak-tls
  # usages:
  #   - digital signature
  #   - key encipherment
  # renewBefore: 0h55m0s
  # duration: 1h0m0s
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: keycloak
  namespace: iam
spec:
  hosts:
    - iam-auth.endvrpad.rconway.uk
  secret:
    name: keycloak-tls
    namespace: iam
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: keycloak
  namespace: iam
spec:
  http:
    - name: keycloak
      match:
        hosts:
          - iam-auth.endvrpad.rconway.uk
        paths:
          - "/*"
      backends:
        - serviceName: keycloak
          servicePort: 80
      plugins:
        - name: redirect
          config:
            http-to-https: true
