apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iam
secretGenerator:
  - name: kc-postgres
    literals:
      - password=changeme
      - postgres-password=changeme
generatorOptions:
  disableNameSuffixHash: true
